---
name: Check Markdown Links
on:
  push:
    branches:
      - main
    paths:
      - '**.markdown'
  pull_request:
    paths:
      - '**.markdown'
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    name: Check markdown links
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        folder-path: 'docs'
        file-extension: 'markdown'
        use-quiet-mode: 'yes'
        config-file: '.github/workflows/markdown.links.config.json'
      continue-on-error: true

