---
name: Check Markdown Links
on:
  push:
    branches:
      - main
    paths:
      - '**.markdown'
  pull_request:
    paths:
      - '**.markdown'
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
    name: Broken Links Check

