---
name: Check Markdown Links
on:
  push:
    branches:
      - master
    paths:
      - '**.markdown'
  pull_request:
    paths:
      - '**.markdown'
jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'
          config-file: '.mlc_config.json'
